### PR TITLE
Range-check the RGBA values

### PR DESCRIPTION
**Pull request by ChayimFriedman2**

### CODE REVIEW

**Comment by avivbeeri** [comment]
This PR is helpful, but annoyingly timed. I am currently in the middle of converting the `Color` class to a subclass of `Vector`, so I will add in this change afterwards.

**Comment by ChayimFriedman2** [comment]
:P this is something definitely useful.

**Comment by avivbeeri** [comment]
For reference, this is the PR I wish to resolve first: https://github.com/domeengine/dome/pull/135

**Comment by avivbeeri** [comment]
I'm debating at the moment whether it makes more sense to throw an error here, or instead clamp the values into the valid range of `0..255`

Clamping means that performing arithmetic values on different colors (such as adding them together) is less error prone, because they'd just reach the maximum.

**Comment by ChayimFriedman2** [comment]
What's the point with adding two colors?

**Comment by avivbeeri** [comment]
I'm not sure personally. However, other kinds of vector arithmetic might be performed and result in unusual results. The question is whether it's DOME's responsibility to catch that for the user.

**Comment by ChayimFriedman2** [comment]
I think the answer is very simple: _depending on the cost_.

If the cost is only when creating colors, I think it's negligible. However, if when you gray-scale an image this check is performed _for each pixel_, then the best for the user will be to enjoy from a performant engine and debugging experience 😄.

**Comment by avivbeeri** [comment]
For now at least, we can range-check on construction. I've merged it in with the `Color is Vector` changes I was making, so if you are happy with it, I can merge it in.

**Pull request merged**
