### PR TITLE
Added Squirrel5 pseudo RNG

### PR DESCRIPTION
**Pull request by TheKing0x9**
This pull adds Squirrel5 pseudo RNG, accessible via the `squirrel5` module. The functionality of this module has been kept at par with the current `squirrel3` RNG.

Please check if the modifications made to `main.c` and `generateEmbedModules.sh` are sufficient to add a new module to Dome.

### CODE REVIEW

**Comment by avivbeeri** [comment]
I would prefer this to be part of the Random module, but just as a separate distinct class. Separating them out isn't very useful.

**Comment by TheKing0x9** [comment]
Apologies for the late reply, but since both of them have the exact same functions, how should I go about structuring the documentation. Should I provide the documentation for both of them seperately, or explain both of them with their differences at the start, and then state that `both of them have these common functionalities` followed by the documentation of the members?

**Comment by avivbeeri** [comment]
There shouldn't be any particular differences, beyond explaining that DOME
has two options for the random algorithm, so that's the approach I would
take.

"Squirrel3 (default) and Squirrel5 both provide the same API, which is
explained below:"

**Comment by TheKing0x9** [comment]
Fixed!

**Review by avivbeeri — APPROVED** [review]

**Comment by avivbeeri** [comment]
Thank you for doing this :)

**Pull request merged**
