### PR TITLE
Make font loading/unloading public

### PR DESCRIPTION
**Pull request by BenStigsen**
#160

### CODE REVIEW

**Comment by BenStigsen** [comment]
Should probably add a comment. Currently it's not possible to load a custom font because the class functions are private. I'm not sure if `unload()` should be public, but `load()` probably should.

**Comment by avivbeeri** [comment]
This PR isn't valid, although I appreciate the work that goes into it. `static` means that the _class_ `Font` has the method, rather than individual instances of that class.

**Comment by BenStigsen** [comment]
Oh, sorry about that. Yeah, I should probably just have waited for your issue reply since you responded very quickly. If I find something else I'll look properly into it first :)

**Comment by avivbeeri** [comment]
I'm not always this speedy, but I usually respond within about 12 hours.

I am glad that you are engaging with the docs and source though :)

**Pull request closed without merging**
